spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username:  root
    password:  root123
#    password: SW#cfg1506
    initialSize:  5
    maxActive:  50
    minIdle:  5
    maxWait:  60000
    poolPreparedStatements:  true
    maxPoolPreparedStatementPerConnectionSize:  20
    validationQuery:  SELECT 1 FROM DUAL
    testOnBorrow:  false
    testOnReturn:  false
    testWhileIdle:  true
    timeBetweenEvictionRunsMillis:  60000
    filters:  stat,wall
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
logging:
  config: classpath:log4j2.yml
server:
  port: 18888
static:
  img-server: http://localhost:8000
  video-server: http://localhost:8000
